resolver: lts-8.18
packages:
- '.'
- location: '../../'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-vty'
    - 'yi-keymap-emacs'
    - 'yi-language'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
extra-deps: []